# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebbaa5306b70667dec85471b849f21a3fd548d67981b78ad0e68b2f140023520039df0857663a317ed64537582bb563e951992e2217d99d04fbc8f086d6b8701

test:
  secret_key_base: 8903ccf5915cc91063ee34175cb6103cf6b511799dcbd5bde47df0d7b19886fb2f76b135263302ea4872720ec4a3ffe79749752e9461dabca04553fab8fdc994

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
